const LIST_AUTO = [
  {
    id: 'el1',
    img: 'img/listAuto/el1.png',
    type: 'Закрытые грузопассажирские автомобили',
    name: 'Opel COMBO Airco Elct Ramen Stuurbediening',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    location: 'Garage van Nierop Netherlands',
    price: 1500,
  },
  {
    id: 'el2',
    img: 'img/listAuto/el2.png',
    type: 'Закрытые грузопассажирские автомобили',
    name: 'Mercedes-Benz V 250 d lang Avantgarde Edition 360°',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    location: 'Garage van Nierop Netherlands',
    price: 54300,
  },
  {
    id: 'el3',
    img: 'img/listAuto/el3.png',
    type: 'Закрытые пассажирские автомобили',
    name: 'Cobus Mercedes Benz 2700 S',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    location: 'Garage van Nierop Netherlands',
    price: 43580,
  },
  {
    id: 'el4',
    img: 'img/listAuto/el4.png',
    type: 'Закрытые пассажирские автомобили',
    name: 'Setra 317 UL-GT/Klima/6 Gang/65 Sitz',
    yearProd: 2011,
    weight: 4500,
    mileage: 320000,
    location: 'Garage van Nierop Netherlands',
    price: 13900,
  },
  {
    id: 'el5',
    img: 'img/listAuto/el5.png',
    type: 'Грузовой фургон',
    name: 'Nissan Eco T 100 Paardenvervoer',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    location: 'Garage van Nierop Netherlands',
    price: 3100,
  },
  {
    id: 'el6',
    img: 'img/listAuto/el6.png',
    type: 'Грузовой фургон',
    name: 'Renault Mascott 130.35 DC 363 / open laadbak 130',
    yearProd: 2015,
    weight: 2000,
    mileage: 490574,
    location: 'Garage van Nierop Netherlands',
    price: 4850,
  },
  {
    id: 'el7',
    img: 'img/listAuto/el7.jpg',
    type: 'Седан',
    name: 'Volkswagen Golf Plus VI Team',
    yearProd: 2010,
    weight: 900,
    mileage: 49000,
    location: 'Garage van Nierop Netherlands',
    price: 7990,
  },
  {
    id: 'el8',
    img: 'img/listAuto/el8.jpeg',
    type: 'Универсал',
    name: 'Audi A4 Avant 2.0 TDI S tronic S-Line',
    yearProd: 2017,
    weight: 1000,
    mileage: 138000,
    location: 'Garage van Nierop Netherlands',
    price: 18990,
  },
  {
    id: 'el9',
    img: 'img/listAuto/el9.jpeg',
    type: 'Универсал',
    name: 'Ford Ford Focus Wagon 1.6 tdci',
    yearProd: 2006,
    weight: 850,
    mileage: 130000,
    location: 'Garage van Nierop Netherlands',
    price: 2500,
  },
  {
    id: 'el10',
    img: 'img/listAuto/el10.jpeg',
    type: 'Универсал',
    name: 'Fiat Fiat Tipo 1.6 Mjet',
    yearProd: 2017,
    weight: 700,
    mileage: 110000,
    location: 'Garage van Nierop Netherlands',
    price: 10400,
  },
];
